### ISSUE TITLE
Install unsuccessful

### ISSUE THREAD

**Issue by lcy101u** [netlify/edge-functions-examples#21]
Got an issue when I tried 
`npm install netlify-cli -g`
[2022-05-08T09_25_51_774Z-debug.log](https://github.com/netlify/edge-functions-examples/files/8646730/2022-05-08T09_25_51_774Z-debug.log)

![image](https://user-images.githubusercontent.com/12782646/167290120-f9f28292-d215-40cc-842a-10b9d7068f88.png)

**Comment by maxcell** [comment]
Howdy @lcy101u, this is a weird bug 🤔 Would you mind trying to install the CLI again with `npm install -g netlify-cli`? If that ends up not working out, it might be best to report it over with our CLI project [here](https://github.com/netlify/cli/issues/new?assignees=&labels=type%3A+bug&template=bug_report.yml&title=Please+replace+with+a+clear+and+descriptive+title).
